### ISSUE TITLE
Ask questions

### ISSUE THREAD

**Issue by kaikkkk** [FarihaAnis/An-IoT-Network-Intrusion-Detection-and-Classification-System-with-XGBoost-using-CICIoT2023-Dataset#1]
I am a master's student from China. I would like to ask if there will be any further updates on this project? Because I only saw some code similar to data analysis, will there be code for attack detection in the future? Because I want to learn your code to improve my coding level, I hope you can reply to me after seeing it, thank you!

**Comment by FarihaAnis** [comment]
Thanks for your interest! I am actively working on adding code for the attack detection system to this project. Stay tuned for updates! If you have any questions or need assistance with your coding journey, feel free to ask.
